import React from 'react'
import NavBar from './NavBar'
import Logo from '../images/tcLogo.PNG';

import {
    makeStyles 
} from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
    paragraphs : {
        paddingTop: '20px',
        fontSize: '18px'
    }, 
    points : {
        paddingTop: '20px',
        paddingLeft : '100px'
    },
    liPoints : {
        paddingTop: '20px',
        paddingLeft : '130px'
    }, 
    pointsHeading : {
        paddingTop: '20px',
        fontSize: '20px'
    }, 
    footer : {
        backgroundColor: "#1b2330",
        heigth: '50px', 
        width: '1499px',
        textAlign : 'right', 
        padding: '30px', 
        color : "white", 
        fontSize: '18px'
    }
}))
const TermsAndCondition = () => {
    const classes = useStyles();
    return (
        <div>
            <NavBar /><br />
            <div style={{paddingTop:'70px', paddingBottom:'30px', paddingLeft: '140px', paddingRight: '140px', textAlign:'justify'}}>
                <h4 style={{color:"#e04c54"}}><b>Terms and Conditions</b></h4>
                <p className={classes.paragraphs}>
                    These terms and conditions (collectively, hereinafter referred to as the <b>"Terms"</b>) 
                    govern your access to and use of the website, www.redbus.com and mobile applications 
                    that link to or reference these Terms <b>("Website")</b>. 
                    Further, the Website is operated by <b>Ibibo Group Pte. Limited 
                    (Company registration no: 201505177D) (hereinafter "redBus") ("Redbus")</b>.
                </p>
                <p className={classes.paragraphs}>
                    The <b>'Seller'</b> referred to in the entire Terms below is the local bus operator who is registered with the Website and whose inventory is listed on the Website.
                </p>
                <p className={classes.paragraphs}>
                    Please read these Terms carefully before using Website, which is an online marketplace' as per the applicable laws, as amended from time to time (hereinafter referred to as the <b>"Online Marketplace"</b>). Further, for the purpose of clarity, it is hereby stated that Website is not engaged in providing any services by itself but is a platform, which merely connects the business to customers.
                </p>
                <p className={classes.paragraphs}>
                    These Terms are an electronic record in terms of the applicable legislation. This electronic record is generated by a computer system and does not require any physical or digital signatures. By using the Website, you signify your agreement to be bound by these conditions.
                </p>
                <p className={classes.paragraphs}>
                    PLEASE NOTE THAT YOUR USE OF THE WEBSITE IN ANY WAY SIGNIFIES YOUR ACCEPTANCE TO OUR TERMS. By agreeing to these Terms, you also agree to our other Website policies; including but not limited to, (i) Privacy Policy, as amended from time to time; and (ii) Cookie Policy.
                </p>
                <p className={classes.paragraphs}>
                    The Users of the Website shall be deemed to have read, understood and expressly accepted these Terms, which shall govern the desired transaction of bus ticket booking/hotel reservations through the Website for all purposes, and shall be binding on the User. All rights and liabilities of the User and/or Website with respect to use of Website and the use of the bus ticket booking/hotel reservation facility (<b>"Facility"</b>) provided by Website shall be restricted to the scope of this agreement.
                </p>
                <p className={classes.paragraphs}>
                    PLEASE NOTE THAT YOUR USE OF THE WEBSITE IN ANY WAY SIGNIFIES YOUR ACCEPTANCE TO OUR TERMS. By agreeing to these In addition to this Terms, any other 'terms of service' of the application-programming interface (<b>"API"</b>) with which Redbus may tie-up would form an integral part of this Agreement (hereinafter referred to as the <b>"API Terms"</b>). However, in the event of a conflict between such API Terms and this Agreement, the terms of this Agreement shall prevail.
                </p>
                <p className={classes.paragraphs}>
                    In addition to these Terms, any other 'terms of service' of the application-programming interface (<b>"API"</b>) with which Redbus may tie-up would form an integral part of this Agreement (hereinafter referred to as the <b>"API Terms"</b>). However, in the event of a conflict between such API Terms and these Terms, these Terms shall prevail.
                </p>
                <p className={classes.paragraphs}>
                    Both User and Website are individually referred as 'party' to the agreement and collective referred to as 'parties'.
                </p>
                <p className={classes.points}>
                    <ol>
                        <li className={classes.pointsHeading}><b>Terminology:</b></li>
                        <p>
                            For the purpose of these Terms, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer and/or availer of Facility being offered on the Website.
                        </p>
                        <li className={classes.pointsHeading}><b>Our Website:</b></li>
                        <p>
                            Redbus wishes to clarify that it is only an online marketplace which merely connects the business to customers. In light of the foregoing, Redbus wishes to clarify the following:

                            The Website is a marketplace, which lists the inventory of local operators who are registered with the Website, but does not own the services per se. Hence, the role of the Website is to connect the You and ‘seller’. Further, the Website provides customer support in the event of complaints against bus operators, cancellation of bus ticket bookings, refunds and charge backs (responsibilities further mentioned in Clause 9, point 6).  
                        </p>
                    </ol>
                </p>
            </div>
            <div className={classes.footer}>
                <p style={{paddingRight:'430px'}}>
                    <img src={Logo} /><br />
                </p>   
                redBus is the world's largest online bus ticket <br/>
                booking service trusted by over 25 million <br />
                happy customers globally. redBus offers bus <br />
                ticket booking through its website,iOS and <br />
                Android mobile apps for all major routes.
            </div>
        </div>
        
    )
}

export default TermsAndCondition